//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjVersion
    {
        public int IdVersion { get; set; }
        public string Version { get; set; }
        public int ProjectId { get; set; }
        public bool Release { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
