//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusIssue
    {
        public StatusIssue()
        {
            this.Issue = new HashSet<Issue>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Issue> Issue { get; set; }
    }
}
