//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Component = new HashSet<Component>();
            this.DetailIssue = new HashSet<DetailIssue>();
            this.Issue = new HashSet<Issue>();
            this.Project = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Psw { get; set; }
        public string Email { get; set; }
        public string Fullname { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Component> Component { get; set; }
        public virtual ICollection<DetailIssue> DetailIssue { get; set; }
        public virtual ICollection<Issue> Issue { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
