//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ComponentLeadId { get; set; }
        public int ProjectId { get; set; }

        public Component(int id, string name, string description, int componentLeadId, int projectId)
        {
            Id = id;
            Name = name;
            Description = description;
            ComponentLeadId = componentLeadId;
            ProjectId = projectId;
        }

        public Component()
        { }
    
    }
}
