//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeIssue
    {
        public int Id { get; set; }
        public string Type { get; set; }
    }
}
